### PR TITLE
Use app.yml flat file to configure app

### PR DESCRIPTION
**Pull request by jgrevich**
__Why__

* This follows the pattern that we've used for other apps where a flat file is used for configuration and its data is seeded from our s3 secrets bucket. This removes the code that expects ENV vars to be set on the host machine.

__How__

* Replace code that expects ENV var with code that reads from the app.yml config file.

### CODE REVIEW

**Comment by monfresh** [comment]
LGTM so far, but I think we also need something like this in order to be able to modify the config and have the app fetch it when it is recycled: https://github.com/18F/identity-idp/blob/560656b0069a143690910ebdb73fc03eb4dfb0da/deploy/activate

**Comment by monfresh** [comment]
Ha! I just noticed that we already have a `deploy/activate` script here that allows us to fetch and set the `.env`. The reason why this app wasn't working in the lower envs is because the data in S3 was not set. I just uploaded a `.env` to S3 and recycled the app in `int`. I'll report back in about 20 minutes to see if that worked.

**Comment by monfresh** [comment]
That alone will not work because the Chef recipe for this app doesn't call the `deploy/activate` script. I submitted a PR to the devops repo: https://github.com/18F/identity-devops/pull/778

**Comment by jgrevich** [comment]
No longer needed unless we decide to use yaml based configs for all our apps for the sake of consistency. For now this has been fixed by https://github.com/18F/identity-devops/pull/778 and I can move on with other issues.

**Pull request closed without merging**
