### PR TITLE
Login.go INT server requires basic auth to use

### PR DESCRIPTION
**Pull request by nickbristow**

### CODE REVIEW

**Comment by pkarman** [comment]
this is same issue as #11

**Comment by pkarman** [comment]
the difference in #11 is that I was just putting the user/pass in the url e.g. `https://user:pass@idp.int.login.gov`

**Comment by nickbristow** [comment]
@pkarman ah yeah, i didn't see that. We ran into an issue while trying to use int.login.gov to test an issue today.

**Comment by pkarman** [comment]
I think this PR can be closed as duplicate of #11 which was just merged.

**Comment by nickbristow** [comment]
agreed @pkarman

**Pull request closed without merging**
